; PlatformIO Project Configuration File
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; To build 'cd' to the 'Hatchling' folder and run a command like:
;	pio run -e microbitV2-ble -t upload
; to build and install the MicroBlocks VM a given board (e.g. microbit or microbitV2-ble) or
;	pio run
; to compile MicroBlocks for all platforms.

[platformio]
src_dir = hatchlingvm
;src_dir = UARTTester

[env]
framework = arduino
monitor_speed = 115200

; micro:bit v1 has insufficient RAM to support BLE
[env:microbit]
platform = nordicnrf51
board = bbcmicrobit
; build_flags = -Wl,-Map,output.map ; uncomment this line to generate a memory map

[env:microbitV2-ble]
platform = https://github.com/h2zero/platform-n-able.git#1.0.0
board = bbcmicrobitv2
; Note: Flags -UNRF52 -DNRF52_SERIES are required to make the
; arduinonordicnrf5 framework use code for the NRF52833 chip.
build_flags = -UNRF52 -DNRF52_SERIES -D CONFIG_WDT_TIMEOUT_SECONDS=0 -D BLE_IDE
lib_deps =
	Adafruit GFX Library
	Adafruit SSD1306
	Adafruit BusIO
	h2zero/NimBLE-Arduino@^1.4.0
