; PlatformIO Project Configuration File
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = hatchlingvm

[env]
framework = arduino
monitor_speed = 115200

; micro:bit v1

[env:microbit110]
platform = nordicnrf51
board = bbcmicrobit
build_flags = -Wno-unused-function -D S110

; micro:bit v2
; Note: Flags -UNRF52 -DNRF52_SERIES are required to make the
; arduinonordicnrf5 framework target the NRF52833 (i.e. the micro:bit v2)

[env:microbit113]
platform = nordicnrf52
board = bbcmicrobit_v2
build_flags = -UNRF52 -D NRF52_SERIES -D S113

[env:microbit140]
platform = nordicnrf52
board = bbcmicrobit_v2
build_flags = -UNRF52 -D NRF52_SERIES -D S140
